apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-backcore-configuration" (include "general.names.short" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  TRYTOND_DATABASE__API_USER: "{{ default "" .Values.postgresql.auth.api_user}}"
  TRYTOND_DATABASE__URI: "postgresql://{{ default "" .Values.postgresql.auth.username }}:{{ default "" .Values.postgresql.auth.password }}@{{ default (printf "%s-%s" .Release.Name "postgresql") .Values.postgresql.host }}:{{ default "5432" .Values.postgresql.service.ports.postgresql }}/{{ default .Release.Name .Values.postgresql.auth.database }}"
  TRYTOND_ASYNC__CELERY: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ include "coog.rabbitmq.host" . }}:{{ .Values.rabbitmq.service.port | default "5672" }}{{ $vhostPath := include "coog.rabbitmq.vhostPath" . }}{{ if $vhostPath }}/{{ $vhostPath }}{{ end }}"
  TRYTOND_ASYNC_CELERY: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ include "coog.rabbitmq.host" . }}:{{ .Values.rabbitmq.service.port | default "5672" }}{{ $vhostPath2 := include "coog.rabbitmq.vhostPath" . }}{{ if $vhostPath2 }}/{{ $vhostPath2 }}{{ end }}"
  {{- if not (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.extraEnvVar .Values.secrets.backCore.extraEnvVar.TRYTOND_SESSION__PASSPHRASE) }}
  {{ include "secret.token.generator" (dict "key" "TRYTOND_SESSION__PASSPHRASE" "secretName" (printf "%s-backcore-configuration" (include "general.names.short" .)) "namespace" .Release.Namespace) }}
  {{- end }}
  {{- if not (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.extraEnvVar .Values.secrets.backCore.extraEnvVar.TRYTOND_API__MAGIC_LINK_SECRET) }}
  {{ include "secret.token.generator" (dict "key" "TRYTOND_API__MAGIC_LINK_SECRET" "secretName" (printf "%s-backcore-configuration" (include "general.names.short" .)) "namespace" .Release.Namespace) }}
  {{- end }}
  {{- range $key, $value := (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.extraEnvVar) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.backCore.migrator.enabled }}
  TRYTOND_MIGRATION__HOST: {{ default (printf "%s-%s" .Release.Name "postgresql") .Values.postgresql.host | quote }}
  {{- if (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.migrator.extraEnvVar .Values.secrets.backCore.migrator.extraEnvVar.TRYTOND_MIGRATION__PASSWORD) }}
  TRYTOND_MIGRATION__PASSWORD: {{ .Values.secrets.backCore.migrator.extraEnvVar.TRYTOND_MIGRATION__PASSWORD | quote }}
  {{- else }}
  TRYTOND_MIGRATION__PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  {{- if (and .Values.secrets .Values.secrets.backCore .Values.secrets.backCore.migrator.extraEnvVar .Values.secrets.backCore.migrator.extraEnvVar.TRYTOND_MIGRATION__USER) }}
  TRYTOND_MIGRATION__USER: {{ .Values.secrets.backCore.migrator.extraEnvVar.TRYTOND_MIGRATION__USER | quote }}
  {{- else }}
  TRYTOND_MIGRATION__USER: {{ .Values.postgresql.auth.username | quote }}
  {{- end }}
  {{- end }}
