{{- if (or .Values.frontCore.enabled
          .Values.apiB2c.enabled
          .Values.apiReferential.enabled
          .Values.b2c.enabled
          .Values.b2b.enabled
          .Values.customerBackend.enabled
          .Values.customerFrontend.enabled)
-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration" (include "general.names.fullname" .) }}
  labels: {{- include "general.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  {{- if not (and .Values.secrets .Values.secrets.frontCore .Values.secrets.frontCore.gateway .Values.secrets.frontCore.gateway.extraEnvVar.JWT_ENCRYPTION) }}
  {{- if (and  .Values.secrets .Values.secrets.frontCore .Values.secrets.frontCore.extraEnvVar .Values.secrets.frontCore.extraEnvVar.JWT_INTERNAL_ENCRYPTION) }}
  JWT_ENCRYPTION: {{ .Values.secrets.frontCore.extraEnvVar.JWT_INTERNAL_ENCRYPTION }}
  {{- else }}
  {{ include "secret.token.generator" (dict "key" "JWT_INTERNAL_ENCRYPTION" "secretName" (printf "%s-configuration" (include "general.names.fullname" .)) "namespace" .Release.Namespace) }}
  {{- end }}
  {{- end }}
  {{- range $key, $value := (and .Values.secrets .Values.secrets.frontCore .Values.secrets.frontCore.gateway .Values.secrets.frontCore.gateway.extraEnvVar) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
